# Generated by Django 4.1.7 on 2023-03-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_accountdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
