# Generated by Django 4.1.7 on 2023-03-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_accountdetails_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='encryption_key',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='password',
            field=models.BinaryField(),
        ),
    ]
